// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMugG5odR0kAHcotIKVRw-agiAByW1B4',
    appId: '1:793246799579:web:fb327c4481743674fb1efe',
    messagingSenderId: '793246799579',
    projectId: 'myquizapp-f5c3b',
    authDomain: 'myquizapp-f5c3b.firebaseapp.com',
    storageBucket: 'myquizapp-f5c3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE24bQmrxZtpK0NqVVYhDhBVR39TMw6_M',
    appId: '1:793246799579:android:cf3630b6d9feb6abfb1efe',
    messagingSenderId: '793246799579',
    projectId: 'myquizapp-f5c3b',
    storageBucket: 'myquizapp-f5c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfeffLvylhzKjnBvO4MJ1SDQu1GuMNS8s',
    appId: '1:793246799579:ios:df61a04b3908f1e5fb1efe',
    messagingSenderId: '793246799579',
    projectId: 'myquizapp-f5c3b',
    storageBucket: 'myquizapp-f5c3b.appspot.com',
    iosClientId: '793246799579-1edi6cjacigjfr79vl6b8umjgkruottt.apps.googleusercontent.com',
    iosBundleId: 'com.crowquiz.quizAppFutter3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfeffLvylhzKjnBvO4MJ1SDQu1GuMNS8s',
    appId: '1:793246799579:ios:df61a04b3908f1e5fb1efe',
    messagingSenderId: '793246799579',
    projectId: 'myquizapp-f5c3b',
    storageBucket: 'myquizapp-f5c3b.appspot.com',
    iosClientId: '793246799579-1edi6cjacigjfr79vl6b8umjgkruottt.apps.googleusercontent.com',
    iosBundleId: 'com.crowquiz.quizAppFutter3',
  );
}
